# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_run
permissions:
  contents: write
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run:
        go get github.com/junglehornet/goscan@v1.0.1;
        go get github.com/junglehornet/junglemath@v0.5.0-beta;
        make build;
        git config --global user.name 'github-actions';
        git config --global user.email 'github-actions@users.noreply.github.com';
        git add cmd/jcalc/build/;
        git commit -am "Automated build";
        git push;
